const KEY='data_analyst_job_tracker_v1', STATUS=['Saved','Applied','Recruiter Contacted','Follow-up','Interview','Offer','Rejected','Closed'], COLORS={'Saved':'#9aa8ba','Applied':'#1677f9','Recruiter Contacted':'#258bb5','Follow-up':'#f0a000','Interview':'#18a86b','Offer':'#7650df','Rejected':'#dc3545','Closed':'#8a96a6'};
let jobs=JSON.parse(localStorage.getItem(KEY)||'[]'),page=1,editing=null;
const $=id=>document.getElementById(id), today=()=>new Date().toISOString().slice(0,10);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=d=>d?new Date(d+'T00:00:00').toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}):'—';
function biz(start,n){let d=new Date(start+'T00:00:00'),i=0;while(i<n){d.setDate(d.getDate()+1);if(d.getDay()>0&&d.getDay()<6)i++}return d.toISOString().slice(0,10)}
function save(){localStorage.setItem(KEY,JSON.stringify(jobs))} function toast(s){$('toast').textContent=s;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2200)}
function badge(s){return `<span class="badge s-${s.replaceAll(' ','-')}">${esc(s)}</span>`} function pri(s){return `<span class="badge p-${s}">${esc(s)}</span>`}
function actions(id){return `<div class="actions"><button class="mini" onclick="viewJob('${id}')">◉</button><button class="mini" onclick="openModal('${id}')">✎</button><button class="mini del" onclick="delJob('${id}')">⌫</button></div>`}
function row(j,detail=true){let over=j.followupDate&&j.followupDate<today()&&!['Offer','Rejected','Closed'].includes(j.status);return `<tr><td class="company"><b>${esc(j.company)}</b>${j.jobLink?`<a href="${esc(j.jobLink)}" target="_blank" rel="noopener">Job link ↗</a>`:''}</td><td>${esc(j.jobTitle)}</td><td>${esc(j.location)||'—'}</td><td>${fmt(j.dateApplied)}</td><td class="${over?'overdue':''}">${fmt(j.followupDate)}${over?' • overdue':''}</td><td>${badge(j.status)}</td><td>${pri(j.priority)}</td>${detail?`<td>${j.recruiterName?'Yes':'No'}</td>`:''}<td>${actions(j.id)}</td></tr>`}
function nav(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$(v).classList.add('active');document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===v));const t={dashboard:['Data Analyst Job Search','Track applications, follow-ups, interviews and stay organized.'],applications:['Applications','Manage every application and recruiter interaction.'],followups:['Follow-ups','Never miss an important follow-up date.'],analytics:['Analytics','Understand your job-search pipeline and conversion.'],backup:['Export / Import','Back up your tracker or move data between devices.']};$('title').textContent=t[v][0];$('subtitle').textContent=t[v][1];if(innerWidth<821)$('sidebar').classList.remove('open');renderAll()}
function openModal(id=null){editing=id;$('form').reset();$('id').value=id||'';$('modalTitle').textContent=id?'Edit Application':'Add Application';$('status').innerHTML=STATUS.map(x=>`<option>${x}</option>`).join('');let j=id?jobs.find(x=>x.id===id):null;$('applied').value=j?.dateApplied||today();$('follow').value=j?.followupDate||biz($('applied').value,5);$('status').value=j?.status||'Applied';$('priority').value=j?.priority||'Medium';$('source').value=j?.source||'LinkedIn';$('contacted').value=j?.contacted||'No';$('connection').value=j?.connection||'No';$('referral').value=j?.referral||'No';if(j)['company','job','link','location','recruiter','recruiterProfile','interview','notes'].forEach(k=>$(k).value=j[k]||'');$('modal').classList.add('open');setTimeout(()=>$('company').focus(),30)}
function closeModal(){$('modal').classList.remove('open');editing=null}
$('form').addEventListener('submit',e=>{e.preventDefault();let d={id:editing||crypto.randomUUID?.()||Date.now().toString(),company:$('company').value.trim(),jobTitle:$('job').value.trim(),jobLink:$('link').value.trim(),location:$('location').value.trim(),dateApplied:$('applied').value,followupDate:$('follow').value||biz($('applied').value,5),recruiterName:$('recruiter').value.trim(),recruiterProfile:$('recruiterProfile').value.trim(),contacted:$('contacted').value,connection:$('connection').value,status:$('status').value,interview:$('interview').value,referral:$('referral').value,source:$('source').value,priority:$('priority').value,notes:$('notes').value.trim()};if(editing)jobs[jobs.findIndex(x=>x.id===editing)]=d;else jobs.unshift(d);save();closeModal();renderAll();toast(editing?'Application updated.':'Application added.')});
$('close').onclick=$('cancel').onclick=closeModal;$('modal').onclick=e=>{if(e.target.id==='modal')closeModal()};$('add').onclick=$('qadd').onclick=()=>openModal();$('menu').onclick=()=>$('sidebar').classList.toggle('open');
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>nav(b.dataset.view));document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>nav(b.dataset.jump));
$('applied').onchange=()=>{if(!editing||!$('follow').value)$('follow').value=biz($('applied').value,5)};
function filtered(){let q=$('search').value.toLowerCase(),s=$('fStatus').value,l=$('fLocation').value,p=$('fPriority').value,src=$('fSource').value,fd=$('fDate').value;return jobs.filter(j=>{let h=[j.company,j.jobTitle,j.location,j.recruiterName,j.notes,j.status,j.source].join(' ').toLowerCase();return(!q||h.includes(q))&&(!s||j.status===s)&&(!l||j.location===l)&&(!p||j.priority===p)&&(!src||j.source===src)&&(!fd||j.followupDate===fd)})}
function renderApps(){let old=$('fLocation').value,loc=[...new Set(jobs.map(j=>j.location).filter(Boolean))].sort();$('fLocation').innerHTML='<option value="">All Locations</option>'+loc.map(x=>`<option>${esc(x)}</option>`).join('');$('fLocation').value=loc.includes(old)?old:'';let list=filtered(),n=+$('size').value,pg=Math.max(1,Math.ceil(list.length/n));page=Math.min(page,pg);$('count').textContent=`${list.length} application${list.length===1?'':'s'}`;$('all').innerHTML=list.slice((page-1)*n,page*n).map(j=>row(j,true)).join('')||'<tr><td colspan="9">No applications match your filters.</td></tr>';$('pages').innerHTML=Array.from({length:pg},(_,i)=>`<button class="page ${i+1===page?'active':''}" onclick="page=${i+1};renderApps()">${i+1}</button>`).join('')}
function renderDash(){let t=jobs.length,i=jobs.filter(j=>j.status==='Interview').length,o=jobs.filter(j=>j.status==='Offer').length,r=jobs.filter(j=>j.status==='Rejected').length,s=jobs.filter(j=>j.status==='Saved').length,due=jobs.filter(j=>j.followupDate&&j.followupDate<=today()&&!['Offer','Rejected','Closed'].includes(j.status)).length,over=jobs.filter(j=>j.followupDate&&j.followupDate<today()&&!['Offer','Rejected','Closed'].includes(j.status)).length;[['mTotal',t],['mInterview',i],['mOffer',o],['mReject',r],['mSaved',s],['mFollow',due],['mOverdue',`${over} overdue`],['mRate',`${t?(i/t*100).toFixed(1):0}% conversion`],['donutN',t]].forEach(([id,v])=>$(id).textContent=v);let c=Object.fromEntries(STATUS.map(x=>[x,jobs.filter(j=>j.status===x).length]));$('legend').innerHTML=STATUS.filter(x=>c[x]).map(x=>`<div><span class="dot" style="background:${COLORS[x]}"></span>${x}<b>${c[x]}</b></div>`).join('')||'<small>No applications yet.</small>';let a=0,parts=[];STATUS.forEach(x=>{let deg=t?c[x]/t*360:0;if(deg){parts.push(`${COLORS[x]} ${a}deg ${a+deg}deg`);a+=deg}});$('donut').style.background=parts.length?`conic-gradient(${parts.join(',')})`:'#dfe6ef';$('recent').innerHTML=jobs.slice(0,8).map(j=>row(j,false)).join('')||'<tr><td colspan="8">No applications yet. Click Add Application to start.</td></tr>';monthly()}
function monthly(){let now=new Date(),ms=[];for(let i=5;i>=0;i--){let d=new Date(now.getFullYear(),now.getMonth()-i,1);ms.push({l:d.toLocaleString('en',{month:'short'}),y:d.getFullYear(),m:d.getMonth(),n:0})}jobs.forEach(j=>{let d=new Date((j.dateApplied||'2000-01-01')+'T00:00:00'),x=ms.find(a=>a.y===d.getFullYear()&&a.m===d.getMonth());if(x)x.n++});let max=Math.max(1,...ms.map(x=>x.n));$('chart').innerHTML=ms.map(x=>`<div class="barcol"><em>${x.n}</em><div class="bar" style="height:${Math.max(3,x.n/max*145)}px"></div><span>${x.l}</span></div>`).join('')}
function renderFollow(){let list=jobs.filter(j=>j.followupDate&&!['Offer','Rejected','Closed'].includes(j.status)).sort((a,b)=>a.followupDate.localeCompare(b.followupDate));$('followList').innerHTML=list.map(j=>`<div class="follow"><div><b>${esc(j.company)} — ${esc(j.jobTitle)}</b><small>${badge(j.status)} ${j.recruiterName?'Recruiter: '+esc(j.recruiterName):''}</small></div><div class="followdate ${j.followupDate<today()?'overdue':''}">${fmt(j.followupDate)}<br><button class="link" onclick="openModal('${j.id}')">Edit</button></div></div>`).join('')||'<p>No pending follow-ups. Great job!</p>'}
function renderAnalytics(){let t=jobs.length,c=jobs.filter(j=>j.contacted==='Yes').length,i=jobs.filter(j=>j.status==='Interview').length,o=jobs.filter(j=>j.status==='Offer').length,ref=jobs.filter(j=>j.referral==='Yes').length;let st=[['Applications',t],['Recruiter contacted',c],['Interviews',i],['Offers',o]];$('funnel').innerHTML=st.map(([l,n])=>`<div class="frow"><div><span>${l}</span><b>${n}</b></div><div class="track"><div class="fill" style="width:${t?Math.max(1,n/t*100):0}%"></div></div></div>`).join('');$('performance').innerHTML=`<div class="stat"><b>${t?(i/t*100).toFixed(1):0}%</b><small>Interview rate</small></div><div class="stat"><b>${t?(o/t*100).toFixed(1):0}%</b><small>Offer rate</small></div><div class="stat"><b>${c}</b><small>Recruiter contacts</small></div><div class="stat"><b>${ref}</b><small>Successful referrals</small></div>`;$('insights').innerHTML=[['Application volume',`You have ${t} tracked applications. Keep the pipeline active.`],['High-priority roles',`${jobs.filter(j=>j.priority==='High').length} applications are marked High priority.`],['Follow-up pipeline',`${jobs.filter(j=>j.status==='Follow-up').length} applications are currently in Follow-up.`]].map(x=>`<div class="insight"><b>${x[0]}</b><span>${x[1]}</span></div>`).join('')}
function exportCSV(){let f=['id','company','jobTitle','jobLink','location','dateApplied','followupDate','recruiterName','recruiterProfile','contacted','connection','status','interview','referral','source','priority','notes'];let q=v=>`"${String(v??'').replaceAll('"','""')}"`;let csv=[f.join(','),...jobs.map(j=>f.map(k=>q(j[k])).join(','))].join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`data-analyst-job-tracker-${today()}.csv`;a.click();toast('CSV exported.')}
function parseCSV(t){let out=[],r=[],c='',q=false;for(let i=0;i<t.length;i++){let x=t[i],n=t[i+1];if(x==='"'&&q&&n==='"'){c+='"';i++;continue}if(x==='"'){q=!q;continue}if(x===','&&!q){r.push(c);c='';continue}if((x==='\n'||x==='\r')&&!q){if(x==='\r'&&n==='\n')i++;r.push(c);if(r.some(v=>v.trim()))out.push(r);r=[];c='';continue}c+=x}if(c||r.length){r.push(c);if(r.some(v=>v.trim()))out.push(r)}return out}
function importFile(file){let rd=new FileReader();rd.onload=e=>{let rows=parseCSV(e.target.result);if(rows.length<2)return toast('No application rows found.');let h=rows[0].map(x=>x.trim()),add=rows.slice(1).map(r=>{let o={};h.forEach((k,i)=>o[k]=r[i]||'');o.id=crypto.randomUUID?.()||Date.now()+Math.random();o.followupDate=o.followupDate||biz(o.dateApplied||today(),5);o.status=o.status||'Applied';o.priority=o.priority||'Medium';return o}).filter(x=>x.company&&x.jobTitle);jobs=[...add,...jobs];save();renderAll();nav('applications');toast(`${add.length} applications imported.`)};rd.readAsText(file)}
function viewJob(id){let j=jobs.find(x=>x.id===id);alert(`${j.company} — ${j.jobTitle}\nStatus: ${j.status}\nLocation: ${j.location||'—'}\nApplied: ${fmt(j.dateApplied)}\nFollow-up: ${fmt(j.followupDate)}\nRecruiter: ${j.recruiterName||'—'}\nConnection: ${j.connection||'No'}\nReferral: ${j.referral||'No'}\n\n${j.notes||''}`)}
function delJob(id){let j=jobs.find(x=>x.id===id);if(j&&confirm(`Delete the application for ${j.company}?`)){jobs=jobs.filter(x=>x.id!==id);save();renderAll();toast('Application deleted.')}}
function renderAll(){renderDash();renderApps();renderFollow();renderAnalytics()}
$('search').oninput=()=>{page=1;renderApps()};['fStatus','fLocation','fPriority','fSource','fDate'].forEach(id=>$(id).onchange=()=>{page=1;renderApps()});$('size').onchange=()=>{page=1;renderApps()};$('clear').onclick=()=>{['fStatus','fLocation','fPriority','fSource','fDate'].forEach(id=>$(id).value='');renderApps()};$('export1').onclick=$('export2').onclick=exportCSV;$('import1').onclick=()=>$('hiddenFile').click();$('hiddenFile').onchange=e=>{if(e.target.files[0])importFile(e.target.files[0]);e.target.value=''};$('import2').onclick=()=>{$('file').files[0]?importFile($('file').files[0]):toast('Choose a CSV file first.')};$('clearAll').onclick=()=>{if(confirm('Delete ALL applications? Export a backup first if needed.')){jobs=[];save();renderAll();toast('All applications deleted.')}};$('theme').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('dark',document.body.classList.contains('dark'));$('theme').innerHTML=document.body.classList.contains('dark')?'☀ <span>Light Mode</span>':'◐ <span>Dark Mode</span>'};if(localStorage.getItem('dark')==='true'){$('theme').click()}
$('fStatus').innerHTML='<option value="">All Statuses</option>'+STATUS.map(x=>`<option>${x}</option>`).join('');renderAll();
